package main

import (
	"github.com/saichler/l8erp/go/types/scm"
	"github.com/saichler/l8types/go/ifs"
)

func registerScmTypes(resources ifs.IResources) {
	// Procurement
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmPurchaseRequisition{}, "RequisitionId")
	resources.Registry().Register(&scm.ScmPurchaseRequisitionList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmRequisitionLine{}, "LineId")
	resources.Registry().Register(&scm.ScmRequisitionLineList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmRequestForQuotation{}, "RfqId")
	resources.Registry().Register(&scm.ScmRequestForQuotationList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmPurchaseOrder{}, "PurchaseOrderId")
	resources.Registry().Register(&scm.ScmPurchaseOrderList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmPurchaseOrderLine{}, "LineId")
	resources.Registry().Register(&scm.ScmPurchaseOrderLineList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmBlanketOrder{}, "BlanketOrderId")
	resources.Registry().Register(&scm.ScmBlanketOrderList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmSupplierScorecard{}, "ScorecardId")
	resources.Registry().Register(&scm.ScmSupplierScorecardList{})

	// Inventory Management
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmItem{}, "ItemId")
	resources.Registry().Register(&scm.ScmItemList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmItemCategory{}, "CategoryId")
	resources.Registry().Register(&scm.ScmItemCategoryList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmStockMovement{}, "MovementId")
	resources.Registry().Register(&scm.ScmStockMovementList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmLotNumber{}, "LotId")
	resources.Registry().Register(&scm.ScmLotNumberList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmSerialNumber{}, "SerialId")
	resources.Registry().Register(&scm.ScmSerialNumberList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmCycleCount{}, "CycleCountId")
	resources.Registry().Register(&scm.ScmCycleCountList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmReorderPoint{}, "ReorderPointId")
	resources.Registry().Register(&scm.ScmReorderPointList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmInventoryValuation{}, "ValuationId")
	resources.Registry().Register(&scm.ScmInventoryValuationList{})

	// Warehouse Management
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmWarehouse{}, "WarehouseId")
	resources.Registry().Register(&scm.ScmWarehouseList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmBin{}, "BinId")
	resources.Registry().Register(&scm.ScmBinList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmReceivingOrder{}, "ReceivingOrderId")
	resources.Registry().Register(&scm.ScmReceivingOrderList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmPutawayTask{}, "TaskId")
	resources.Registry().Register(&scm.ScmPutawayTaskList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmPickTask{}, "TaskId")
	resources.Registry().Register(&scm.ScmPickTaskList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmPackTask{}, "TaskId")
	resources.Registry().Register(&scm.ScmPackTaskList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmShipTask{}, "TaskId")
	resources.Registry().Register(&scm.ScmShipTaskList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmWavePlan{}, "WavePlanId")
	resources.Registry().Register(&scm.ScmWavePlanList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmDockSchedule{}, "ScheduleId")
	resources.Registry().Register(&scm.ScmDockScheduleList{})

	// Logistics and Transportation
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmCarrier{}, "CarrierId")
	resources.Registry().Register(&scm.ScmCarrierList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmFreightRate{}, "RateId")
	resources.Registry().Register(&scm.ScmFreightRateList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmShipment{}, "ShipmentId")
	resources.Registry().Register(&scm.ScmShipmentList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmRoute{}, "RouteId")
	resources.Registry().Register(&scm.ScmRouteList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmLoadPlan{}, "LoadPlanId")
	resources.Registry().Register(&scm.ScmLoadPlanList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmDeliveryProof{}, "ProofId")
	resources.Registry().Register(&scm.ScmDeliveryProofList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmFreightAudit{}, "AuditId")
	resources.Registry().Register(&scm.ScmFreightAuditList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmReturnAuthorization{}, "RmaId")
	resources.Registry().Register(&scm.ScmReturnAuthorizationList{})

	// Demand Planning
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmDemandForecast{}, "ForecastId")
	resources.Registry().Register(&scm.ScmDemandForecastList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmForecastModel{}, "ModelId")
	resources.Registry().Register(&scm.ScmForecastModelList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmDemandPlan{}, "PlanId")
	resources.Registry().Register(&scm.ScmDemandPlanList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmPromotionalPlan{}, "PlanId")
	resources.Registry().Register(&scm.ScmPromotionalPlanList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmNewProductPlan{}, "PlanId")
	resources.Registry().Register(&scm.ScmNewProductPlanList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmForecastAccuracy{}, "AccuracyId")
	resources.Registry().Register(&scm.ScmForecastAccuracyList{})

	// Supply Planning
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmMaterialRequirement{}, "RequirementId")
	resources.Registry().Register(&scm.ScmMaterialRequirementList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmDistributionRequirement{}, "RequirementId")
	resources.Registry().Register(&scm.ScmDistributionRequirementList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmSupplyPlan{}, "PlanId")
	resources.Registry().Register(&scm.ScmSupplyPlanList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmSupplierCollaboration{}, "CollaborationId")
	resources.Registry().Register(&scm.ScmSupplierCollaborationList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmSafetyStock{}, "SafetyStockId")
	resources.Registry().Register(&scm.ScmSafetyStockList{})
	resources.Introspector().Decorators().AddPrimaryKeyDecorator(&scm.ScmLeadTime{}, "LeadTimeId")
	resources.Registry().Register(&scm.ScmLeadTimeList{})
}
