/*
© 2025 Sharon Aicler (saichler@gmail.com)

Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
You may obtain a copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// CRM Reports - Column Definitions using Layer8ColumnFactory

(function() {
    'use strict';

    window.CrmReports = window.CrmReports || {};

    var col = Layer8ColumnFactory;
    var enums = CrmReports.enums;

    CrmReports.columns = {
        CrmReport: [
            ...col.enum('reportType', 'Report Type', enums.REPORT_TYPE,
                function(v) { return Layer8DRenderers.renderEnum(v, enums.REPORT_TYPE); }),
            ...col.col('title', 'Title'),
            ...col.col('periodName', 'Period'),
            ...col.date('periodStart', 'Period Start'),
            ...col.date('periodEnd', 'Period End'),
            ...col.col('currencyId', 'Currency'),
            ...col.col('departmentId', 'Department'),
            ...col.col('generatedBy', 'Generated By'),
            ...col.date('generatedAt', 'Generated'),
            ...col.money('grandTotal', 'Grand Total'),
            ...col.number('rowCount', 'Rows'),
            // sections is generated server-side and nested two deep, so it gets
            // a count here rather than an inline table in the form: the POST
            // handler overwrites whatever was submitted.
            ...col.custom('sections', 'Sections',
                function(item) { return (item.sections || []).length; },
                { sortKey: 'rowCount' }),
            ...col.col('notes', 'Notes')
        ]
    };
})();
