/*
© 2025 Sharon Aicler (saichler@gmail.com)

Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
You may obtain a copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Project Reports - Form Definitions using Layer8FormFactory

(function() {
    'use strict';

    window.PrjReports = window.PrjReports || {};

    var f = Layer8FormFactory;
    var enums = PrjReports.enums;

    PrjReports.forms = {
        PrjReport: f.form('Project Report', [
            f.section('Report Parameters', [
                ...f.select('reportType', 'Report Type', enums.REPORT_TYPE, true),
                ...f.text('periodName', 'Period'),
                ...f.date('periodStart', 'Period Start'),
                ...f.date('periodEnd', 'Period End'),
                ...f.reference('currencyId', 'Currency', 'Currency'),
                ...f.reference('departmentId', 'Department', 'Department'),
                ...f.reference('generatedBy', 'Generated By', 'Employee'),
                ...f.textarea('notes', 'Notes')
            ]),
            // Filled by generatePrjReport() on POST. Read-only because anything
            // typed here is discarded when the report is generated, and a
            // control whose value is silently dropped is worse than none.
            f.section('Generated', [
                { key: 'title', label: 'Title', type: 'text', readOnly: true },
                { key: 'generatedAt', label: 'Generated At', type: 'date', readOnly: true },
                { key: 'rowCount', label: 'Rows', type: 'number', readOnly: true },
                { key: 'grandTotal', label: 'Grand Total', type: 'money', readOnly: true },
                // sections is a child type, so it renders as an inline table in the
                // parent's form (PrimeObjectReferences Rule 3) -- without it the
                // report's own content is invisible everywhere in the UI. Its
                // `lines` are a second level down, which the inline table cannot
                // nest; Layer8FinReportViewer was written for that and is
                // currently dead code.
                ...f.inlineTable('sections', 'Sections', [
                    { key: 'sectionId', label: 'Section ID', hidden: true },
                    { key: 'title', label: 'Title' },
                    { key: 'sectionTotal', label: 'Section Total', type: 'money' }
                ])
            ])
        ])
    };

    // Without this the registry falls back to 'id', getItemId() returns
    // undefined, and every row click, Edit and Delete silently does nothing.
    PrjReports.primaryKeys = {
        PrjReport: 'reportId'
    };
})();
