//
//© 2025 Sharon Aicler (saichler@gmail.com)
//
//Layer 8 Ecosystem is licensed under the Apache License, Version 2.0.
//You may obtain a copy of the License at:
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: sys-moduleconfig.proto

package sys

import (
	erp "github.com/saichler/l8erp/go/types/erp"
	l8api "github.com/saichler/l8types/go/types/l8api"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Stores which modules/sub-modules/services are disabled.
// By default everything is enabled. Only disabled paths are stored.
type SysModuleConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConfigId string `protobuf:"bytes,1,opt,name=config_id,json=configId,proto3" json:"config_id,omitempty"`
	// Dot-notation paths of disabled elements:
	//
	//	"bi"                    - entire BI module disabled
	//	"hcm.learning"          - HCM Learning sub-module disabled
	//	"hcm.core-hr.documents" - just the Documents service disabled
	DisabledPaths []string       `protobuf:"bytes,2,rep,name=disabled_paths,json=disabledPaths,proto3" json:"disabled_paths,omitempty"`
	AuditInfo     *erp.AuditInfo `protobuf:"bytes,3,opt,name=audit_info,json=auditInfo,proto3" json:"audit_info,omitempty"`
}

func (x *SysModuleConfig) Reset() {
	*x = SysModuleConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_moduleconfig_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysModuleConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysModuleConfig) ProtoMessage() {}

func (x *SysModuleConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sys_moduleconfig_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysModuleConfig.ProtoReflect.Descriptor instead.
func (*SysModuleConfig) Descriptor() ([]byte, []int) {
	return file_sys_moduleconfig_proto_rawDescGZIP(), []int{0}
}

func (x *SysModuleConfig) GetConfigId() string {
	if x != nil {
		return x.ConfigId
	}
	return ""
}

func (x *SysModuleConfig) GetDisabledPaths() []string {
	if x != nil {
		return x.DisabledPaths
	}
	return nil
}

func (x *SysModuleConfig) GetAuditInfo() *erp.AuditInfo {
	if x != nil {
		return x.AuditInfo
	}
	return nil
}

type SysModuleConfigList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List     []*SysModuleConfig `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Metadata *l8api.L8MetaData  `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *SysModuleConfigList) Reset() {
	*x = SysModuleConfigList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_moduleconfig_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysModuleConfigList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysModuleConfigList) ProtoMessage() {}

func (x *SysModuleConfigList) ProtoReflect() protoreflect.Message {
	mi := &file_sys_moduleconfig_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysModuleConfigList.ProtoReflect.Descriptor instead.
func (*SysModuleConfigList) Descriptor() ([]byte, []int) {
	return file_sys_moduleconfig_proto_rawDescGZIP(), []int{1}
}

func (x *SysModuleConfigList) GetList() []*SysModuleConfig {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SysModuleConfigList) GetMetadata() *l8api.L8MetaData {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_sys_moduleconfig_proto protoreflect.FileDescriptor

var file_sys_moduleconfig_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x79, 0x73, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x63, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x73, 0x79, 0x73, 0x1a, 0x09, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x65, 0x72, 0x70, 0x2d, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x01, 0x0a, 0x0f, 0x53,
	0x79, 0x73, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x64,
	0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x50, 0x61, 0x74,
	0x68, 0x73, 0x12, 0x2d, 0x0a, 0x0a, 0x61, 0x75, 0x64, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x72, 0x70, 0x2e, 0x41, 0x75, 0x64,
	0x69, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x75, 0x64, 0x69, 0x74, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x6e, 0x0a, 0x13, 0x53, 0x79, 0x73, 0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x73, 0x79, 0x73, 0x2e, 0x53, 0x79, 0x73,
	0x4d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x04, 0x6c, 0x69,
	0x73, 0x74, 0x12, 0x2d, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6c, 0x38, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x38, 0x4d,
	0x65, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x73, 0x79, 0x73,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sys_moduleconfig_proto_rawDescOnce sync.Once
	file_sys_moduleconfig_proto_rawDescData = file_sys_moduleconfig_proto_rawDesc
)

func file_sys_moduleconfig_proto_rawDescGZIP() []byte {
	file_sys_moduleconfig_proto_rawDescOnce.Do(func() {
		file_sys_moduleconfig_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_moduleconfig_proto_rawDescData)
	})
	return file_sys_moduleconfig_proto_rawDescData
}

var file_sys_moduleconfig_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sys_moduleconfig_proto_goTypes = []interface{}{
	(*SysModuleConfig)(nil),     // 0: sys.SysModuleConfig
	(*SysModuleConfigList)(nil), // 1: sys.SysModuleConfigList
	(*erp.AuditInfo)(nil),       // 2: erp.AuditInfo
	(*l8api.L8MetaData)(nil),    // 3: l8api.L8MetaData
}
var file_sys_moduleconfig_proto_depIdxs = []int32{
	2, // 0: sys.SysModuleConfig.audit_info:type_name -> erp.AuditInfo
	0, // 1: sys.SysModuleConfigList.list:type_name -> sys.SysModuleConfig
	3, // 2: sys.SysModuleConfigList.metadata:type_name -> l8api.L8MetaData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sys_moduleconfig_proto_init() }
func file_sys_moduleconfig_proto_init() {
	if File_sys_moduleconfig_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sys_moduleconfig_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysModuleConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sys_moduleconfig_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysModuleConfigList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_moduleconfig_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_moduleconfig_proto_goTypes,
		DependencyIndexes: file_sys_moduleconfig_proto_depIdxs,
		MessageInfos:      file_sys_moduleconfig_proto_msgTypes,
	}.Build()
	File_sys_moduleconfig_proto = out.File
	file_sys_moduleconfig_proto_rawDesc = nil
	file_sys_moduleconfig_proto_goTypes = nil
	file_sys_moduleconfig_proto_depIdxs = nil
}
